from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List, Dict, Any
from parser_engine import CFGParserEngine

app = FastAPI(title="CFG Ambiguity Checker API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class GrammarRule(BaseModel):
    lhs: str = Field(..., example="S")
    rhs: str = Field(..., example="S + S | a | b")

class AmbiguityRequest(BaseModel):
    start_symbol: str = Field(default="S", example="S")
    rules: List[GrammarRule]
    target_string: str = Field(..., example="a+a")

class AmbiguityResponse(BaseModel):
    target_string: str
    is_ambiguous: bool
    tree_count: int
    trees: List[Dict[str, Any]]
    earley_chart: List[Dict[str, Any]]
    execution_steps: List[Dict[str, Any]] = []
    explanation: str

def parse_input_rules(raw_rules: List[GrammarRule]) -> Dict[str, List[List[str]]]:
    parsed: Dict[str, List[List[str]]] = {}
    for r in raw_rules:
        lhs = r.lhs.strip()
        if not lhs:
            continue
        if lhs not in parsed:
            parsed[lhs] = []
        for alt in r.rhs.split("|"):
            tokens = CFGParserEngine.tokenize_rhs(alt)
            parsed[lhs].append(tokens)
    return parsed

@app.post("/api/check-ambiguity", response_model=AmbiguityResponse)
async def check_ambiguity(payload: AmbiguityRequest):
    if not payload.rules:
        raise HTTPException(status_code=400, detail="At least one grammar rule is required.")

    rules_dict = parse_input_rules(payload.rules)
    start_sym = payload.start_symbol.strip()
    if start_sym not in rules_dict:
        raise HTTPException(status_code=400, detail=f"Start symbol '{start_sym}' is not defined in grammar rules.")

    engine = CFGParserEngine(start_symbol=start_sym, rules=rules_dict)
    cleaned_target = payload.target_string.strip()

    # 1. Bounded Brute-force derivation trees
    parse_trees, timed_out = engine.find_all_parse_trees(cleaned_target)
    tree_count = len(parse_trees)
    is_ambiguous = tree_count >= 2

    # 2. Complete Earley Parser State Sets Chart (S_0 ... S_n) and step trace
    chart, execution_steps = engine.generate_earley_chart(cleaned_target)
    print(f"DEBUG: Generated {len(chart)} Earley sets and {len(execution_steps)} execution steps")

    if timed_out and tree_count < 2:
        explanation = (
            f"Search budget reached (timeout). Evaluated trees up to safe bounded depth. "
            f"{'1 parse tree found, but search halted to prevent UI lock.' if tree_count == 1 else 'No tree found within depth limit.'}"
        )
    elif is_ambiguous:
        explanation = (
            f"The grammar is AMBIGUOUS for string '{payload.target_string}'. "
            f"Found {tree_count} distinct parse trees generating the exact same token yield. "
            f"In TOC, a grammar is ambiguous if there exists at least one string in L(G) that has "
            f"two or more distinct leftmost derivations, rightmost derivations, or parse trees."
        )
    elif tree_count == 1:
        explanation = (
            f"Only 1 unique parse tree was found for target string '{payload.target_string}' within the bounded search depth. "
            f"The string is generated by the grammar, but ambiguity was not demonstrated by this specific target string."
        )
    else:
        explanation = (
            f"The target string '{payload.target_string}' cannot be derived from the provided CFG within "
            f"the maximum search depth, or it does not belong to the language L(G)."
        )

    return AmbiguityResponse(
        target_string=payload.target_string,
        is_ambiguous=is_ambiguous,
        tree_count=tree_count,
        trees=[t.to_dict() for t in parse_trees[:2]],
        earley_chart=chart,
        execution_steps=execution_steps,
        explanation=explanation
    )

@app.get("/api/health")
async def health():
    return {"status": "ok", "service": "CFG Ambiguity Checker"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
